name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "47 5 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # The bazel version to use is read from //.bazelversion.
      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Build
        run: "env CARGO_BAZEL_REPIN=true bazel build //..."
      - name: Run
        run: "bazel run //program:my_program"
