name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "47 5 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 7.2.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: "env CARGO_BAZEL_REPIN=true bazel build //..."
      - name: Run
        run: "bazel run //program:my_program"
